### ISSUE TITLE
Version tag .post1 proving troublesome

### ISSUE THREAD

**Issue by TiemenSch** [plotly/Kaleido#114]
I'm trying to build multi-architecture images (linux/amd64 and linux/arm64) that have Kaleido installed by means of a custom Python package dependency but the .post1 release makes it somewhat troublesome. I have my current Kaleido version set to 0.2.1 and higher using Poetry, but PIP isn't switching to the .post1 automatically for ARM64. 

It is proving hard to correctly define the dependencies to let the ARM architecture pickup the .post1 and have the AMD64 one stick to 0.2.1. Wouldn't it just be easier to bump the version up to 0.2.2 (patch version, e.g. no new features) and let package maintainers decide if they update their Kaleido dependency version?

**Comment by jonmmease** [comment]
Hi @TiemenSch, thanks for explaining the difficulty you're running into.  The `.post1` release was only done because a new architecture was added without changes to any of the other architectures.  The versions will all line up again across the board after the next release (which unfortunately I don't have an ETA for).

**Comment by TiemenSch** [comment]
Thanks for clarifying! I'd advocate just releasing a patch version (assuming you've adopted semantic versioning), but I understand it's a tradeoff in purity vs usability regardless. I think we can consider this solved at that :). I'll see if I can work out Poetry's architecture identifiers.
