### ISSUE TITLE
Setting up local topojson when export choropleth static image

### ISSUE THREAD

**Issue by marcellosusanto11** [plotly/Kaleido#56]
I am trying to export plotly.express.choropleth figure to static image to be embedded into HTML. Note that the json file used to make the plot are in my local folder because it is the json for Indonesian state. Because of that I try setting up the pio.kaleido.scope.topojson path to my local file. This is the code that I used

### Code ###
import os
FOLDER_PATH = os.path.dirname(os.path.abspath(__file__))

import plotly.io as pio
pio.kaleido.scope.topojson = f'{FOLDER_PATH}/indonesia-en.json'
tmpfile = pio.to_image(fig, format="png", engine="kaleido")
encoded = base64.b64encode(tmpfile).decode('utf-8')
html = f"""<img src=\'data:image/png;base64,{encoded}\', width=100%, height=100%>"""
### End of Code ###

It throws me this error
Exception: --topojson argument is not a valid URL: /home/marcello.susanto/OJK_FINTECH_SCRAPING/indonesia-en.json

From the error message, I assume that the pio.kaleido.scope.topojson must be an URL so is that mean it is impossible to use local json file ? I hope that in the future this can also get a local path since downloading the json and store it into a folder is much more easier

**Comment by jonmmease** [comment]
Hi @marcellosusanto11, 

Have you been able to get the plot working in interactive HTML form? For example, inside the Jupyter notebook or in a standalone html file produced by `fig.write_html`?

Typically this would be done using the `geojson` argument to the `px.choropleth` function rather than customizing the topojson path. See https://plotly.com/python/choropleth-maps/#choropleth-map-using-geojson.

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
