### ISSUE TITLE
Each plotly to_image() call using Kaleido creates and deletes a /tmp/.org.chromium.Chromium.* directory

### ISSUE THREAD

**Issue by sancheztavo** [plotly/Kaleido#64]
I'm generating huge amounts of temporary plots in memory using plotly figure.to_image() call and found out that it was causing unexpected writes to disk.

I've tracked that it's creating and deleting multiple directories of the form `/tmp/.org.chromium.Chromium.XXXXXX`.  Is there a way to avoid this (and any other disk write? Else, can I force it to always use /dev/shm ?

**Comment by jonmmease** [comment]
Hi @sancheztavo, could you try removing the `--disable-dev-shm-usage` chromium flag? See https://github.com/plotly/Kaleido/wiki/Customizing-Chromium-Flags.

```python
import plotly.io as pio
pio.kaleido.scope.chromium_args = tuple([
    arg for arg in scope.chromium_args if arg != "--disable-dev-shm-usage"
])
```

Thanks!

**Comment by sancheztavo** [comment]
That fixed it, @jonmmease it was kind of confusing since without removing `--disable-dev-shm-usage` it would write to both `/tmp/` and `/dev/shm` (I've seen that after doing `lsof -p PID`) at the same time

**Comment by jonmmease** [comment]
Glad to hear it @sancheztavo.

I honestly haven't dug into the internals of what chromium's `--disable-dev-shm-usage` flag does.  It's added by default because a lot of Docker configurations don't work otherwise, but it would be nice to try to document it's behavior wrt kaleido.

Going to close this in favor of https://github.com/plotly/Kaleido/issues/65 for the documentation consideration. Thanks!
