### ISSUE TITLE
kaleido not found on FreeBSD

### ISSUE THREAD

**Issue by jmgurney** [plotly/Kaleido#77]
Just tried to install kaleido on FreeBSD, and got:
```
# pip install kaleido
ERROR: Could not find a version that satisfies the requirement kaleido
ERROR: No matching distribution found for kaleido
```

This is w/:
```
# python --version
Python 3.8.7
# pip --version
pip 21.0.1 from /usr/home/freebsd/sscanf/p/lib/python3.8/site-packages/pip (python 3.8)
```

Not sure how to proceed as I'd expect that the above would checkout and build kaleido as needed like all the other python packages, and it's not clear why it isn't found.

**Comment by jonmmease** [comment]
Hi @jmgurney,

> I'd expect that the above would checkout and build kaleido as needed like all the other python packages

This would be nice, unfortunately it's not practical to distribute a source bundle of kaleido because it would require including the full chromium source code as well. So the source package would be over 30GB and would take over 4 hours to compile.  On Linux, there are also a few dozen external dependencies that need to be installed using the system package manager. 

So anyway, this is why we only publish wheels

It would be great to make kaleido available on FreeBSD. Here are a few considerations:

First, Is there a binary platform tag specific to FreeBSD (https://packaging.python.org/specifications/platform-compatibility-tags/)?

Could you run this and update the issue with what it returns?  This should be a long list of the compatibility tags supported by your operating system.
```python
import packaging.tags
list(packaging.tags.compatible_tags())
```

Second, what does it take to build [chromium headless](https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md) on FreeBSD. I don't think the chromium project provides official build instructions for FreeBSD, but it looks like there is a port (https://wiki.freebsd.org/Chromium).  But, it also looks like the port hasn't been updated since last August, and requires a few dozen patches to the chromium source tree (https://github.com/gliaskos/freebsd-chromium).

Given the existence of this Port, it should be possible to build kaleido on FreeBSD, but it would require some commitment from some folks on the FreeBSD side to develop and maintain the patch set, and to help work out the continuous integration side of things.

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
